ARCHITECTURE = avr
BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/tty.usbserial-A8005MO9
ARDUINO_DIR  = ../../../arduino-1.6.5
include ~/DroneTime/MultiWii_2_4/Arduino-Makefile/Arduino.mk
